apiVersion: v1
kind: Secret
metadata:
  name: plural-env
  labels:
{{ include "plural.labels" . | indent 4 }}
type: Opaque
data:
  AWS_REGION: {{ .Values.region | b64enc | quote }}
  PROVIDER: {{ .Values.provider | b64enc | quote }}
  BUCKET: {{ .Values.api.bucket | b64enc | quote }}
  DKR_DNS: {{ .Values.ingress.dkr_dns | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwt | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 10 | b64enc | quote }}
  ERLANG_COOKIE: {{ .Values.secrets.erlang | b64enc | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secrets.jwt_pk | b64enc | quote }}
  JWT_CERT: {{ .Values.secrets.jwt_cert | b64enc | quote }}
  JWT_ISS: {{ .Values.secrets.jwt_iss | b64enc | quote }}
  JWT_AUD: {{ .Values.secrets.jwt_aud | b64enc | quote }}
  AES_KEY: {{ .Values.secrets.aes_key | b64enc | quote }}
{{ if .Values.secrets.stripe_secret }}
  STRIPE_SECRET: {{ .Values.secrets.stripe_secret | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.stripe_connect_id }}
  STRIPE_CONNECT_ID: {{ .Values.secrets.stripe_connect_id | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.stripe_publishable_key }}
  STRIPE_PUBLISHABLE_KEY: {{ .Values.secrets.stripe_publishable_key | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.sendgrid_secret }}
  SENGRID_API_KEY: {{ .Values.secrets.sendgrid_secret | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.zoom_client_id }}
  ZOOM_CLIENT_ID: {{ .Values.secrets.zoom_client_id | b64enc | quote }}
  ZOOM_CLIENT_SECRET: {{ .Values.secrets.zoom_client_secret | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.cloudflare_token }}
  CLOUDFLARE_AUTH_TOKEN: {{ .Values.secrets.cloudflare_token | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.cloudflare_zone }}
  CLOUDFLARE_ZONE: {{ .Values.secrets.cloudflare_zone | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.zerossl_access_key }}
  ZEROSSL_ACCESS_KEY: {{ .Values.secrets.zerossl_access_key | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.github }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.github.client_id | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.github.client_secret | b64enc | quote }}
{{ end }}
{{ if .Values.secrets.google }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.google.client_id | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.google.client_secret | b64enc | quote }}
{{ end }}
{{ if .Values.admin.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: plural-migration-env
  labels:
{{ include "plural.labels" . | indent 4 }}
type: Opaque
data:
  ADMIN_EMAIL: {{ .Values.admin.email | b64enc | quote }}
  ADMIN_NAME: {{ .Values.admin.name | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  PUBLISHER_NAME: {{ .Values.admin.publisher | b64enc | quote }}
  PUBLISHER_DESCRIPTION: {{ .Values.admin.publisher_description | b64enc | quote }}
{{ end }}
{{ if .Values.hydraPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hydra.plural-hydra.credentials.postgresql.acid.zalan.do
  labels:
{{ include "plural.labels" . | indent 4 }}
stringData:
  username: hydra
  password: {{ .Values.hydraPassword }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: plural-hydra
  labels:
{{ include "plural.labels" . | indent 4 }}
stringData:
  secretsSystem: {{ .Values.hydraSecrets.system | quote }}
  secretsCookie: {{ .Values.hydraSecrets.cookie | quote }}
  dsn: {{ .Values.hydraSecrets.dsn | quote }}
