apiVersion: v1
appVersion: "1.0"
description: A helm chart for installing forge
name: forge
sources:
- https://github.com/michaeljguarino/forge
maintainers:
- name: michaeljguarino
  email: mguarino46@gmail.com
version: 0.3.3
