apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forge-endpoint-reader
  labels:
{{ include "forge.labels" . | indent 4 }}
spec:
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forge
  labels:
{{ include "forge.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forge-endpoint-reader
  labels:
{{ include "forge.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: forge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forge-endpoint-reader