apiVersion: batch/v1
kind: Job
metadata:
  name: chartmart-migration-{{ randAlphaNum 4 | lower }}
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/opt/app/bin/chartmart",  "migrate"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: chartmart-env
        - secretRef:
            name: chartmart-migration-env
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbPasswordSecret }}
              key: postgresql-password
      restartPolicy: Never
  backoffLimit: 5