apiVersion: v2
name: plural
description: A helm chart for installing plural
appVersion: 0.11.6
version: 0.10.91
dependencies:
  - name: hydra
    version: 0.26.5
    repository: https://k8s.ory.sh/helm/charts
  - name: test-base
    version: 0.1.10
    repository: https://pluralsh.github.io/module-library
    condition: test-base.enabled
maintainers:
  - name: michaeljguarino
    email: mjg@plural.sh
sources:
  - https://github.com/pluralsh/plural
