apiVersion: v2
name: plural
description: A helm chart for installing plural
appVersion: "0.8.3"
version: 0.8.84
dependencies:
- name: hydra
  repository: https://k8s.ory.sh/helm/charts
  version: 0.16.0
- name: test-base
  repository: https://pluralsh.github.io/module-library
  version: 0.1.3
  condition: test-base.enabled
maintainers:
- email: mjg@plural.sh
  name: michaeljguarino
sources:
- https://github.com/pluralsh/plural
