apiVersion: v2
appVersion: "1.0"
dependencies:
- name: hydra
  repository: https://k8s.ory.sh/helm/charts
  version: 0.16.0
description: A helm chart for installing plural
maintainers:
- email: mjg@plural.sh
  name: michaeljguarino
name: plural
sources:
- https://github.com/pluralsh/plural
version: 0.7.32
